dist: bionic
language: php

php:
  - 7.3

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true

before_script:
  - composer install --prefer-dist --no-interaction
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
  - chmod +x php-coveralls.phar

script:
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - php-coveralls.phar -v

matrix:
  fast_finish: true
